[package]
name = "dlib"
version = "0.1.0"
repository = "https://github.com/vberger/dlib"
authors = ["Victor Berger <victor.berger@m4x.org>"]
license = "MIT"
description = "Helper macros for handling manually loading optionnal system libraries."


[dependencies]
libc = "0.1"

[features]
dlopen = []