[package]
name = "dlib-test"
version = "0.1.0"
authors = ["Victor Berger <victor.berger@m4x.org>"]
edition = "2018"
publish = false

[dependencies]
dlib = { path = "../" }
lazy_static = { version = "1.0", optional = true }

[features]
"dlopen" = ["lazy_static"]